module.exports = {
	SUCCESS : 0,
	INVALID_CREDENTIALS : 403,
	MISSING_PARAMETERS : 2,
	INTERNAL_SERVER_ERROR : 500,
	EMAIL_EXISTED : 3,
	AUTHENTICATE_FAILED: -1,
	FOUND_RELATED_DATA : -9,
	DATA_EXISTED : -5,
	DATA_NOT_FOUND : -4,
    DATABASE_ERROR : -3,
	PARAMETER_ERROR : -2
};
